apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-deployment
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp-app
  template:
    metadata:
      labels:
        app: gcp-app
    spec:
      containers:
      - name: app-container
        image: gcr.io/gke-project-385918/gcp-project1-dev:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gcp-devops-gke-service"
  namespace: "app-prod"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "gcp-app"
  type: "LoadBalancer"